# Generated by Django 6.0.5 on 2026-05-24 16:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=128)),
                ('age', models.PositiveSmallIntegerField()),
                ('bed', models.CharField(blank=True, max_length=16)),
                ('ward', models.CharField(default='Ward A', max_length=64)),
                ('blood_type', models.CharField(blank=True, max_length=8)),
                ('diagnosis', models.CharField(blank=True, max_length=128)),
                ('dry_weight_kg', models.DecimalField(decimal_places=1, default=70, max_digits=5)),
                ('daily_fluid_limit_ml', models.PositiveIntegerField(default=1000)),
                ('fluid_intake_today_ml', models.PositiveIntegerField(default=0)),
                ('urine_output_24h_ml', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('stable', 'Stable'), ('warning', 'Warning'), ('critical', 'Critical'), ('pending', 'Pending')], default='stable', max_length=16)),
                ('photo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=32, unique=True)),
                ('ward', models.CharField(default='Ward 4B', max_length=64)),
                ('title', models.CharField(default='Charge Nurse', max_length=64)),
                ('avatar_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='FluidLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('drink', 'Drink'), ('food', 'Food'), ('urine', 'Urine'), ('other', 'Other')], max_length=16)),
                ('description', models.CharField(max_length=255)),
                ('volume_ml', models.PositiveIntegerField()),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='mobile', max_length=16)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluid_logs', to='core.patient')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Information')], max_length=16)),
                ('title', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('equipment_ref', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=64)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('urine_ml_24h', models.PositiveIntegerField(default=0)),
                ('temperature_c', models.DecimalField(decimal_places=1, default=36.6, max_digits=4)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='core.patient')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
