# Generated by Django 6.0.5 on 2026-05-26 02:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(blank=True, upload_to='education/')),
                ('thumbnail_name', models.CharField(blank=True, max_length=128)),
                ('content', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, upload_to='nutrition/')),
                ('image_name', models.CharField(blank=True, help_text='Static filename for mobile, e.g. banana.jpg', max_length=128)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('sodium', models.PositiveIntegerField(default=0)),
                ('potassium', models.PositiveIntegerField(default=0)),
                ('phosphorus', models.PositiveIntegerField(default=0)),
                ('estimated_fluid_ml', models.PositiveIntegerField(default=0)),
                ('hd_status', models.CharField(choices=[('aman', 'Aman'), ('batasi', 'Batasi'), ('hindari', 'Hindari')], default='aman', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FoodScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=128)),
                ('scan_type', models.CharField(choices=[('food', 'Food'), ('drink', 'Drink')], default='food', max_length=16)),
                ('estimated_fluid_ml', models.PositiveIntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('nutrition_data', models.JSONField(blank=True, default=dict)),
                ('hd_status', models.CharField(choices=[('aman', 'Aman'), ('batasi', 'Batasi'), ('hindari', 'Hindari')], default='aman', max_length=16)),
                ('image', models.ImageField(blank=True, upload_to='scans/food/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fooditem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_scans', to='core.patient')),
            ],
            options={
                'verbose_name_plural': 'Food scan histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UrineScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_ml', models.PositiveIntegerField()),
                ('confidence', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, upload_to='scans/urine/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urine_scans', to='core.patient')),
            ],
            options={
                'verbose_name_plural': 'Urine scan histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('nurse', 'Nurse')], default='patient', max_length=16)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
