# Generated by Django 6.0.5 on 2026-06-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_educationmodule_fooditem_patient_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image_name',
            field=models.CharField(blank=True, help_text='Static filename or URL for mobile', max_length=512),
        ),
    ]
