# Generated by Django 6.0.5 on 2026-06-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fooditem_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image_name',
            field=models.CharField(blank=True, help_text='Static filename or URL for mobile', max_length=2048),
        ),
    ]
